[parser]
fence_sequence = "```"
fence_sequence_alt = "~~~"

block_name_prefix = "#-"

macro_start = "# ==>"
macro_end = "."

transclusion_start = "@{{"
transclusion_end = "}}"

link_prefix = "@"

file_prefix = "file:"
hidden_prefix = "hidden:"

[paths]
root = "lp/"
code = "../code/"
docs = "../book/"

files = ["SUMMARY.md"]
entrypoint = "Main"

[language.rb]
clear_blank_lines = true
eof_newline = true

    [language.rb.block_labels]
    comment_start = "#"
    block_start = "<@"
    block_next = "<@>"
    block_end = "@>"

[plugin.block-links]
